version: '3'
services:
    jdownloader-2:
      image: jlesage/jdownloader-2
      ports:
         - "5800:5800"
      volumes:
         - "/home/johannes/docker/jdownloader/config:/config:rw"
           #         - "/home/johannes/Downloads:/output:rw"
         - "/media/data/downloads:/output:rw"
      restart: unless-stopped
