version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8080:8080
    volumes:
      - /media:/data
      - /home/johannes/docker/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
